apiVersion: apps/v1
kind: Deployment
metadata:
  name: soldout-test
  labels:
    tags.datadoghq.com/service: "soldout-test"
    tags.datadoghq.com/env: "soldout-test"
    tags.datadoghq.com/version: "test-latest"

spec:
  selector:
    matchLabels:
      app: soldout-test

  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  template:
    metadata:
      labels:
        app: soldout-test
        tags.datadoghq.com/service: "soldout-test"
        tags.datadoghq.com/env: "soldout-test"
        tags.datadoghq.com/version: "test-latest"

    spec:
      containers:
        - name: soldout-test
          image: acrsoldout.azurecr.io/sldt-co-ltd/soldout_webapp-test:latest
          imagePullPolicy: Always
          lifecycle:
            postStart:
              exec:
                command:
                - /bin/sh
                - -c 
                - "/bin/echo 'options single-request-reopen' >> /etc/resolv.conf"
          env:
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP

          resources:
            limits:
              memory: "8000Mi"
              cpu: "4000m"

          ports:
            - containerPort: 80
            - containerPort: 8090

          readinessProbe:
            httpGet:
              path: /kcp/index.html
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 2

      dnsConfig:
        options:
        - name: ndots
          value: "2"            

      terminationGracePeriodSeconds: 50